replicaCount: 2

image:
  repository: minabisa90/flask-app
  tag: "v1"
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  FLASK_ENV: "production"
  LOG_LEVEL: "info"

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

httpRoute:
  enabled: false
